# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/app

    branches:
      only:
        - master
        - /\S+\/homework-\d+/

    docker:
      - image: cypress/base:8
        environment:
          TERM: xterm

    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-packages-v2-{{ checksum "yarn.lock" }}
            - v2-deps-{{ .Branch }}
            - v2-deps

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-v2-{{ checksum "yarn.lock" }}
          paths:
            - ~/.npm
            - ~/.cache

      - run:
          name: Build app
          command: yarn build

      - run:
          name: Start unit tests
          command: yarn test

      - run:
          name: Start background app
          command: yarn start
          background: true

      - run:
          name: Start integration tests
          command: yarn run cypress:run

      - run:
          name: Check env variables
          command: echo $CIRCLE_PR_NUMBER

